<?php
require 'fpdf/fpdf.php';
class PDFHistoriaClinica extends FPDF {
    function Header()
    {
        parent::Header(); // TODO: Change the autogenerated stub
        $this->Image('../images/optica-logo.png', 5, 12, 30);
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(180, 10, 'Historial Clinico', 0, 0, 'C');
        $this->Ln(20);
    }

    function Footer()
    {
        parent::Footer(); // TODO: Change the autogenerated stub
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Pagina ', $this->PageNo().'/{nb}', 0, 0, 'C');
    }
}